strictness: high
test-warnings: true
doc-warnings: false

ignore-paths:
  - docs
  - .tox


#ignore-patterns:
#  - (^|/)skip(this)?(/|$)

pep8:
  disable:
#    - W602
#    - W603
  enable:
#    - W601
  options:
    max-line-length: 120
